name: pr-pipeline

on: pull_request

jobs:
  pr-labeler: 
    name: PR Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/plugins/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build: 
    name: Build PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.18

      - name : Install dependencies
        run: npm i
      
      - name : Lint
        run: npm run lint
      
      - name : Test
        run: npm run coverage